"""initial

Revision ID: 6a1f3b963da3
Revises: 
Create Date: 2025-05-10 00:36:05.304776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a1f3b963da3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('addresses',
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=100), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('agents',
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('agency_name', sa.String(length=100), nullable=True),
    sa.Column('contact_info', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('renters',
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('desired_move_in', sa.Date(), nullable=True),
    sa.Column('preferred_location', sa.String(length=255), nullable=True),
    sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('credit_cards',
    sa.Column('card_number', sa.String(length=20), nullable=False),
    sa.Column('renter_email', sa.String(length=100), nullable=False),
    sa.Column('exp_date', sa.Date(), nullable=True),
    sa.Column('cvv', sa.String(length=3), nullable=True),
    sa.Column('billing_address', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['billing_address'], ['addresses.address_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['renter_email'], ['renters.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_number')
    )
    op.create_table('properties',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('agent_email', sa.String(length=100), nullable=False),
    sa.Column('property_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('available_from', sa.Date(), nullable=True),
    sa.Column('available_to', sa.Date(), nullable=True),
    sa.Column('sqr_footage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_email'], ['agents.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('property_id')
    )
    op.create_table('apartments',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('num_rooms', sa.Integer(), nullable=True),
    sa.Column('building_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('property_id')
    )
    op.create_table('bookings',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('renter_email', sa.String(length=100), nullable=False),
    sa.Column('card_number', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['card_number'], ['credit_cards.card_number'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['renter_email'], ['renters.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_table('commercial_buildings',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('property_id')
    )
    op.create_table('houses',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('num_rooms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('property_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('houses')
    op.drop_table('commercial_buildings')
    op.drop_table('bookings')
    op.drop_table('apartments')
    op.drop_table('properties')
    op.drop_table('credit_cards')
    op.drop_table('renters')
    op.drop_table('agents')
    op.drop_table('addresses')
    op.drop_table('users')
    # ### end Alembic commands ###
