services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: realestate_user
      POSTGRES_PASSWORD: StrongPass!
      POSTGRES_DB: realestate_db
    volumes: [pgdata:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U realestate_user -d realestate_db"]
      interval: 5s
      retries: 5

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://realestate_user:StrongPass!@db/realestate_db
      FLASK_APP: realestate_app/app.py
    ports: ["5000:5000"]
    command: >
      sh -c "flask db upgrade --directory realestate_app/migrations &&
             flask run --host=0.0.0.0 --port=5000"

volumes:
  pgdata:
